version: "3.9"

services:
#
#  STORE RELATED SERVICES
#
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - store-network
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

  store-db:
    image: postgres:16
    container_name: store-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:

      POSTGRES_DB: storedb
      POSTGRES_USER: storeuser
      POSTGRES_PASSWORD: storepass
    networks:
      - store-network
    volumes:
      - pgdata-store:/var/lib/postgresql/data
      - ./sql-init/init-store.sql:/docker-entrypoint-initdb.d/01-init-store.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U storeuser -d storedb"]
      interval: 5s
      timeout: 3s
      retries: 10

  store-app:
    build: ./store
    container_name: store-app
    ports:
      - "8082:8082"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_DATASOURCE_URL: jdbc:postgresql://store-db:5432/storedb
      SPRING_DATASOURCE_USERNAME: storeuser
      SPRING_DATASOURCE_PASSWORD: storepass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8082
    depends_on:
      store-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - store-network



#
#  DELIVERYCO RELATED SERVICES
#
  deliveryco-db:
    image: postgres:16
    container_name: delivery-postgres
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: deliverydb
      POSTGRES_USER: deliveryuser
      POSTGRES_PASSWORD: deliverypass
    networks:
      - store-network
    volumes:
      - pgdata-deliveryco:/var/lib/postgresql/data
      - ./sql-init/init-deliveryco.sql:/docker-entrypoint-initdb.d/01-init-store.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U deliveryuser -d deliverydb"]
      interval: 5s
      timeout: 3s
      retries: 10

  deliveryco-app:
    build: ./deliveryco
    container_name: deliveryco-app
    ports:
      - "8080:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_DATASOURCE_URL: jdbc:postgresql://deliveryco-db:5432/deliverydb
      SPRING_DATASOURCE_USERNAME: deliveryuser
      SPRING_DATASOURCE_PASSWORD: deliverypass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8080
    depends_on:
      deliveryco-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - store-network


networks:
  store-network:

volumes:
  rabbitmqdata:
  pgdata-store:
  pgdata-deliveryco: